config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
devise_for :users, :controllers => {:registrations => "registrations"}

get 'welcome/index'

  resources :users

  resources :hatemanis, only: []

  resources :favmanis, only: []

  resources :manicures, only: []

  resources :tutorials, only: []

  resources :teches, except: [:show] 

  resources :colours, except: [:show]

   root 'welcome#index'

	get '/about', to: 'welcome#about'

end

app/models/hatemani.rb
class Hatemani < ActiveRecord::Base
	belongs_to :user
end

app/controllers/hatemanis_controller.rb
class HatemanisController < ApplicationController
  before_action :set_hatemani, only: [:show, :edit, :update, :destroy]

  # GET /hatemanis
  # GET /hatemanis.json
  def index
    @hatemanis = Hatemani.all
  end

  # GET /hatemanis/1
  # GET /hatemanis/1.json
  def show
  end

  # GET /hatemanis/new
  def new
    @hatemani = Hatemani.new
  end

  # GET /hatemanis/1/edit
  def edit
  end

  # POST /hatemanis
  # POST /hatemanis.json
  def create
    @hatemani = Hatemani.new(hatemani_params)

    respond_to do |format|
      if @hatemani.save
        format.html { redirect_to @hatemani, notice: 'Hatemani was successfully created.' }
        format.json { render :show, status: :created, location: @hatemani }
      else
        format.html { render :new }
        format.json { render json: @hatemani.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hatemanis/1
  # PATCH/PUT /hatemanis/1.json
  def update
    respond_to do |format|
      if @hatemani.update(hatemani_params)
        format.html { redirect_to @hatemani, notice: 'Hatemani was successfully updated.' }
        format.json { render :show, status: :ok, location: @hatemani }
      else
        format.html { render :edit }
        format.json { render json: @hatemani.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hatemanis/1
  # DELETE /hatemanis/1.json
  def destroy
    @hatemani.destroy
    respond_to do |format|
      format.html { redirect_to hatemanis_url, notice: 'Hatemani was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hatemani
      @hatemani = Hatemani.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hatemani_params
      params.require(:hatemani).permit(:techid, :colourid)
    end
end

app/helpers/hatemanis_helper.rb
module HatemanisHelper
end

app/views/hatemanis/_form.html.erb
<%= form_for(@hatemani) do |f| %>
  <% if @hatemani.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hatemani.errors.count, "error") %> prohibited this hatemani from being saved:</h2>

      <ul>
      <% @hatemani.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :techid %><br>
    <%= f.text_field :techid %>
  </div>
  <div class="field">
    <%= f.label :colourid %><br>
    <%= f.text_field :colourid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hatemanis/edit.html.erb
<h1>Editing hatemani</h1>

<%= render 'form' %>

<%= link_to 'Show', @hatemani %> |
<%= link_to 'Back', hatemanis_path %>

app/views/hatemanis/index.html.erb
<h1>Listing hatemanis</h1>

<table>
  <thead>
    <tr>
      <th>Techid</th>
      <th>Colourid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hatemanis.each do |hatemani| %>
      <tr>
        <td><%= hatemani.techid %></td>
        <td><%= hatemani.colourid %></td>
        <td><%= link_to 'Show', hatemani %></td>
        <td><%= link_to 'Edit', edit_hatemani_path(hatemani) %></td>
        <td><%= link_to 'Destroy', hatemani, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hatemani', new_hatemani_path %>

app/views/hatemanis/new.html.erb
<h1>New hatemani</h1>

<%= render 'form' %>

<%= link_to 'Back', hatemanis_path %>

app/views/hatemanis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Techid:</strong>
  <%= @hatemani.techid %>
</p>

<p>
  <strong>Colourid:</strong>
  <%= @hatemani.colourid %>
</p>

<%= link_to 'Edit', edit_hatemani_path(@hatemani) %> |
<%= link_to 'Back', hatemanis_path %>