config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
devise_for :users, :controllers => {:registrations => "registrations"}

get 'welcome/index'

  resources :users

  resources :hatemanis, only: []

  resources :favmanis, only: []

  resources :manicures, only: []

  resources :tutorials, only: []

  resources :teches, except: [:show] 

  resources :colours, except: [:show]

   root 'welcome#index'

	get '/about', to: 'welcome#about'

end

app/models/manicure.rb
class Manicure < ActiveRecord::Base
	belongs_to :user
end

app/controllers/manicures_controller.rb
class ManicuresController < ApplicationController
  before_action :set_manicure, only: [:show, :edit, :update, :destroy]

  # GET /manicures
  # GET /manicures.json
  def index
    @manicures = Manicure.all
  end

  # GET /manicures/1
  # GET /manicures/1.json
  def show
  end

  # GET /manicures/new
  def new
    @manicure = Manicure.new
  end

  # GET /manicures/1/edit
  def edit
  end

  # POST /manicures
  # POST /manicures.json
  def create
    @manicure = Manicure.new(manicure_params)

    respond_to do |format|
      if @manicure.save
        format.html { redirect_to @manicure, notice: 'Manicure was successfully created.' }
        format.json { render :show, status: :created, location: @manicure }
      else
        format.html { render :new }
        format.json { render json: @manicure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manicures/1
  # PATCH/PUT /manicures/1.json
  def update
    respond_to do |format|
      if @manicure.update(manicure_params)
        format.html { redirect_to @manicure, notice: 'Manicure was successfully updated.' }
        format.json { render :show, status: :ok, location: @manicure }
      else
        format.html { render :edit }
        format.json { render json: @manicure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manicures/1
  # DELETE /manicures/1.json
  def destroy
    @manicure.destroy
    respond_to do |format|
      format.html { redirect_to manicures_url, notice: 'Manicure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manicure
      @manicure = Manicure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manicure_params
      params.require(:manicure).permit(:numcol, :numaccents, :techid, :colourid, :accents)
    end
end

app/helpers/manicures_helper.rb
module ManicuresHelper
end

app/views/manicures/_form.html.erb
<%= form_for(@manicure) do |f| %>
  <% if @manicure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manicure.errors.count, "error") %> prohibited this manicure from being saved:</h2>

      <ul>
      <% @manicure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numcol %><br>
    <%= f.text_field :numcol %>
  </div>
  <div class="field">
    <%= f.label :numaccents %><br>
    <%= f.text_field :numaccents %>
  </div>
  <div class="field">
    <%= f.label :techid %><br>
    <%= f.text_field :techid %>
  </div>
  <div class="field">
    <%= f.label :colourid %><br>
    <%= f.text_field :colourid %>
  </div>
  <div class="field">
    <%= f.label :accents %><br>
    <%= f.text_field :accents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manicures/edit.html.erb
<h1>Editing manicure</h1>

<%= render 'form' %>

<%= link_to 'Show', @manicure %> |
<%= link_to 'Back', manicures_path %>

app/views/manicures/index.html.erb
<h1>Listing manicures</h1>

<table>
  <thead>
    <tr>
      <th>Numcol</th>
      <th>Numaccents</th>
      <th>Techid</th>
      <th>Colourid</th>
      <th>Accents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manicures.each do |manicure| %>
      <tr>
        <td><%= manicure.numcol %></td>
        <td><%= manicure.numaccents %></td>
        <td><%= manicure.techid %></td>
        <td><%= manicure.colourid %></td>
        <td><%= manicure.accents %></td>
        <td><%= link_to 'Show', manicure %></td>
        <td><%= link_to 'Edit', edit_manicure_path(manicure) %></td>
        <td><%= link_to 'Destroy', manicure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manicure', new_manicure_path %>

app/views/manicures/new.html.erb
<h1>New manicure</h1>

<%= render 'form' %>

<%= link_to 'Back', manicures_path %>

app/views/manicures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numcol:</strong>
  <%= @manicure.numcol %>
</p>

<p>
  <strong>Numaccents:</strong>
  <%= @manicure.numaccents %>
</p>

<p>
  <strong>Techid:</strong>
  <%= @manicure.techid %>
</p>

<p>
  <strong>Colourid:</strong>
  <%= @manicure.colourid %>
</p>

<p>
  <strong>Accents:</strong>
  <%= @manicure.accents %>
</p>

<%= link_to 'Edit', edit_manicure_path(@manicure) %> |
<%= link_to 'Back', manicures_path %>